#!/usr/bin/env python3
"""Generate ardupilot_mode_tables_gen.h from ardupilotmega.xml.

Usage: gen_mode_tables.py <ardupilotmega.xml> <output.h>
"""

import sys
import xml.etree.ElementTree as ET

GROUPS = [
    ("PLANE_MODE",   "kPlaneNames"),
    ("COPTER_MODE",  "kCopterNames"),
    ("ROVER_MODE",   "kRoverNames"),
    ("SUB_MODE",     "kSubNames"),
    ("TRACKER_MODE", "kTrackerNames"),
]

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <ardupilotmega.xml> <output.h>", file=sys.stderr)
        sys.exit(1)

    xml_path, out_path = sys.argv[1], sys.argv[2]

    tree = ET.parse(xml_path)
    root = tree.getroot()

    # enum_name -> {value(int): description(str)}
    enum_maps: dict[str, dict[int, str]] = {}
    targets = {g[0] for g in GROUPS}
    for enum_elem in root.iter("enum"):
        name = enum_elem.get("name", "")
        if name not in targets:
            continue
        modes: dict[int, str] = {}
        for entry in enum_elem.findall("entry"):
            try:
                val = int(entry.get("value", ""), 0)
            except ValueError:
                continue
            if not (0 <= val <= 255):
                continue
            desc_elem = entry.find("description")
            if desc_elem is not None and desc_elem.text:
                text = " ".join(desc_elem.text.split())  # normalise whitespace
                if text:
                    modes[val] = text
        enum_maps[name] = modes

    lines = [
        "// AUTO-GENERATED by gen_mode_tables.py — do not edit.",
        "// Re-run CMake to regenerate from ardupilotmega.xml.",
        "#pragma once",
        "#include <string_view>",
        "",
        "namespace ap_mode_tables {",
        "",
    ]

    for enum_name, var_name in GROUPS:
        modes = enum_maps.get(enum_name, {})
        lines.append(f"constexpr std::string_view {var_name}[256] = {{")
        for i in range(256):
            escaped = modes.get(i, "").replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    /* {i:3d} */ "{escaped}",')
        lines.append("};")
        lines.append("")

    lines += ["}  // namespace ap_mode_tables", ""]

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

if __name__ == "__main__":
    main()
