/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

#include <filesystem>
#include <nlohmann/json.hpp>
#include <pj_base/sdk/data_source_patterns.hpp>
#include <string>
#include <string_view>
#include <variant>
#include <vector>

#include "ardupilot_dialog.hpp"
#include "ardupilot_manifest.hpp"  // generated by pj_configure_plugin(MANIFEST_HEADER): kArdupilotManifest
#include "pj_drone_core/ardupilot/parser.hpp"
#include "pj_drone_core/io/mapped_file.hpp"

namespace {

namespace ap = pj_drone::ardupilot;

PJ::PrimitiveType toPrimitive(ap::ValueType type) {
  switch (type) {
    case ap::ValueType::kInt8:
      return PJ::PrimitiveType::kInt8;
    case ap::ValueType::kUint8:
      return PJ::PrimitiveType::kUint8;
    case ap::ValueType::kInt16:
      return PJ::PrimitiveType::kInt16;
    case ap::ValueType::kUint16:
      return PJ::PrimitiveType::kUint16;
    case ap::ValueType::kInt32:
      return PJ::PrimitiveType::kInt32;
    case ap::ValueType::kUint32:
      return PJ::PrimitiveType::kUint32;
    case ap::ValueType::kInt64:
      return PJ::PrimitiveType::kInt64;
    case ap::ValueType::kUint64:
      return PJ::PrimitiveType::kUint64;
    case ap::ValueType::kFloat32:
      return PJ::PrimitiveType::kFloat32;
    case ap::ValueType::kFloat64:
      return PJ::PrimitiveType::kFloat64;
  }
  return PJ::PrimitiveType::kFloat64;
}

PJ::sdk::ValueRef toValueRef(const ap::SampleValue& value) {
  return std::visit([](auto v) -> PJ::sdk::ValueRef { return v; }, value);
}

/// Writes the parser's groups to the host datastore: one topic per group, one pre-registered field per column,
/// rows appended by handle.
class HostSink : public ap::SampleSink {
 public:
  explicit HostSink(const PJ::sdk::SourceWriteHostView& host) : host_(host) {}

  size_t declareGroup(const std::string& name, const std::vector<ap::FieldSpec>& fields) override {
    Group group;
    auto topic = host_.ensureTopic(name);
    if (!topic) {
      fail(topic.error());
      groups_.push_back(std::move(group));
      return groups_.size() - 1;
    }
    group.topic = *topic;
    group.handles.reserve(fields.size());
    for (const auto& field : fields) {
      auto handle = host_.ensureField(*topic, field.name, toPrimitive(field.type));
      if (!handle) {
        fail(handle.error());
        break;
      }
      group.handles.push_back(*handle);
    }
    group.valid = error_.empty();
    groups_.push_back(std::move(group));
    return groups_.size() - 1;
  }

  bool append(size_t group_id, int64_t timestamp_ns, const ap::SampleValue* values, size_t count) override {
    if (!error_.empty()) {
      return false;
    }
    const Group& group = groups_[group_id];
    if (!group.valid || group.handles.size() != count) {
      fail("internal error: group/field mismatch");
      return false;
    }
    row_.clear();
    for (size_t i = 0; i < count; ++i) {
      row_.push_back({.field = group.handles[i], .value = toValueRef(values[i])});
    }
    auto status = host_.appendBoundRecord(
        group.topic, PJ::Timestamp{timestamp_ns}, PJ::Span<const PJ::sdk::BoundFieldValue>(row_.data(), row_.size()));
    if (!status) {
      fail(status.error());
      return false;
    }
    return true;
  }

  const std::string& error() const {
    return error_;
  }

 private:
  struct Group {
    PJ::sdk::TopicHandle topic{};
    std::vector<PJ::sdk::FieldHandle> handles;
    bool valid = false;
  };

  void fail(std::string message) {
    if (error_.empty()) {
      error_ = std::move(message);
    }
  }

  const PJ::sdk::SourceWriteHostView& host_;
  std::vector<Group> groups_;
  std::vector<PJ::sdk::BoundFieldValue> row_;
  std::string error_;
};

class ArdupilotSource : public PJ::FileSourceBase {
 public:
  uint64_t extraCapabilities() const override {
    return PJ::kCapabilityDirectIngest | PJ::kCapabilityHasDialog;
  }

  PJ_borrowed_dialog_t getDialog() override {
    return PJ::borrowDialog(dialog_);
  }

  std::string saveConfig() const override {
    return nlohmann::json{{"filepath", filepath_}}.dump();
  }

  PJ::Status loadConfig(std::string_view config_json) override {
    auto cfg = nlohmann::json::parse(config_json, nullptr, false);
    if (cfg.is_discarded()) {
      return PJ::unexpected(std::string("invalid config JSON"));
    }
    filepath_ = cfg.value("filepath", std::string{});
    if (!filepath_.empty()) {
      dialog_.setFilePath(filepath_);
    }
    return PJ::okStatus();
  }

  PJ::Status importData() override {
    if (filepath_.empty()) {
      return PJ::unexpected(std::string("no filepath configured"));
    }

    pj_drone::io::MappedFile file;
    std::string error;
    if (!file.open(std::filesystem::path(std::u8string(filepath_.begin(), filepath_.end())), &error)) {
      return PJ::unexpected("ArduPilot: " + error + ": " + filepath_);
    }
    if (file.size() == 0) {
      return PJ::unexpected(std::string("ArduPilot: file is empty: ") + filepath_);
    }

    (void)runtimeHost().progressStart("Importing ArduPilot log", file.size(), true);

    // Embedded FILE messages are only needed by the dialog, so the import pass does not collect them.
    ap::ParserOptions options;
    options.load_files = false;
    options.hash_instance = false;
    options.progress = [this](size_t pos, size_t /*total*/) {
      (void)runtimeHost().progressUpdate(pos);
      // Stop and keep: whatever was decoded so far stays in the datastore.
      return !runtimeHost().isStopRequested();
    };

    HostSink sink(writeHost());
    ap::Parser parser(file.data(), file.size(), std::move(options), &sink);

    if (parser.result() == ap::Parser::Result::kSinkError) {
      return PJ::unexpected(sink.error());
    }
    return PJ::okStatus();
  }

 private:
  std::string filepath_;
  ardupilot_detail::ArdupilotDialog dialog_;
};

}  // namespace

PJ_DIALOG_PLUGIN(ardupilot_detail::ArdupilotDialog, kArdupilotManifest)
PJ_DATA_SOURCE_PLUGIN(ArdupilotSource, kArdupilotManifest)
