/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

#include <map>
#include <memory>
#include <pj_base/sdk/data_source_patterns.hpp>
#include <string>
#include <variant>
#include <vector>

#include "mavlink_dialog.hpp"
#include "mavlink_manifest.hpp"  // generated by pj_configure_plugin(MANIFEST_HEADER): kMavlinkManifest
#include "pj_drone_core/mavlink/decoder.hpp"
#include "transport.hpp"

namespace {

namespace mav = pj_drone::mavlink;
using mavlink_detail::ConnectionConfig;
using mavlink_detail::Mode;

PJ::PrimitiveType toPrimitive(mav::ValueType type) {
  switch (type) {
    case mav::ValueType::kInt8:
      return PJ::PrimitiveType::kInt8;
    case mav::ValueType::kUint8:
      return PJ::PrimitiveType::kUint8;
    case mav::ValueType::kInt16:
      return PJ::PrimitiveType::kInt16;
    case mav::ValueType::kUint16:
      return PJ::PrimitiveType::kUint16;
    case mav::ValueType::kInt32:
      return PJ::PrimitiveType::kInt32;
    case mav::ValueType::kUint32:
      return PJ::PrimitiveType::kUint32;
    case mav::ValueType::kInt64:
      return PJ::PrimitiveType::kInt64;
    case mav::ValueType::kUint64:
      return PJ::PrimitiveType::kUint64;
    case mav::ValueType::kFloat32:
      return PJ::PrimitiveType::kFloat32;
    case mav::ValueType::kFloat64:
      return PJ::PrimitiveType::kFloat64;
  }
  return PJ::PrimitiveType::kFloat64;
}

PJ::sdk::ValueRef toValueRef(const mav::Value& value) {
  return std::visit([](auto v) -> PJ::sdk::ValueRef { return v; }, value);
}

/// One topic per "mav/<sysid>.<compid>/<MSG>", fields pre-registered from the message's schema on first sight.
struct TopicBinding {
  PJ::sdk::TopicHandle topic{};
  std::vector<PJ::sdk::FieldHandle> fields;
};

class MavlinkSource : public PJ::StreamSourceBase {
 public:
  uint64_t extraCapabilities() const override {
    return PJ::kCapabilityDirectIngest | PJ::kCapabilityHasDialog;
  }

  PJ_borrowed_dialog_t getDialog() override {
    return PJ::borrowDialog(dialog_);
  }

  std::string saveConfig() const override {
    return dialog_.saveConfig();
  }

  PJ::Status loadConfig(std::string_view config_json) override {
    if (!config_json.empty()) {
      (void)dialog_.loadConfig(config_json);
    }
    return PJ::okStatus();
  }

  PJ::Status onStart() override {
    const ConnectionConfig cfg = ConnectionConfig::fromJson(dialog_.saveConfig());

    switch (cfg.mode) {
      case Mode::kUdp:
        transport_ = std::make_unique<mavlink_detail::UdpTransport>(static_cast<uint16_t>(cfg.udp_port));
        break;
      case Mode::kTcp:
        transport_ = std::make_unique<mavlink_detail::TcpTransport>(cfg.tcp_host, static_cast<uint16_t>(cfg.tcp_port));
        break;
      case Mode::kSerial:
        transport_ = std::make_unique<mavlink_detail::SerialTransport>(
            dialog_.systemLocationOf(cfg.serial_port), cfg.serial_port, static_cast<unsigned>(cfg.baud));
        break;
    }

    if (auto status = transport_->open(); !status) {
      transport_.reset();
      // PJ3 showed a message box for TCP and serial failures; a UDP bind failure was silent there.
      if (cfg.mode != Mode::kUdp) {
        runtimeHost().showWarning("MAVLink Streamer", status.error());
      }
      return PJ::unexpected(status.error());
    }

    parser_.reset();
    bindings_.clear();
    return PJ::okStatus();
  }

  // Parsing and writing happen here, on the host thread; the transport only buffers raw bytes.
  PJ::Status onPoll() override {
    if (!transport_) {
      return PJ::okStatus();
    }
    auto batch = transport_->queue.drain();
    while (!batch.empty()) {
      const auto& chunk = batch.front();
      messages_.clear();
      parser_.feed(chunk.data.data(), chunk.data.size(), messages_);
      for (const auto& message : messages_) {
        if (auto status = write(message, chunk.timestamp_ns); !status) {
          return status;
        }
      }
      batch.pop();
    }
    return PJ::okStatus();
  }

  void onStop() override {
    if (transport_) {
      transport_->close();
      transport_.reset();
    }
    bindings_.clear();
  }

 private:
  PJ::Status write(const mav::Message& message, int64_t recv_ns) {
    auto it = bindings_.find(message.topic);
    if (it == bindings_.end()) {
      TopicBinding binding;
      auto topic = writeHost().ensureTopic(message.topic);
      if (!topic) {
        return PJ::unexpected(topic.error());
      }
      binding.topic = *topic;
      binding.fields.reserve(message.schema->size());
      for (const auto& spec : *message.schema) {
        auto field = writeHost().ensureField(*topic, spec.name, toPrimitive(spec.type));
        if (!field) {
          return PJ::unexpected(field.error());
        }
        binding.fields.push_back(*field);
      }
      it = bindings_.emplace(message.topic, std::move(binding)).first;
    }

    const TopicBinding& binding = it->second;
    row_.clear();
    row_.reserve(message.values.size());
    for (size_t i = 0; i < message.values.size(); ++i) {
      row_.push_back({binding.fields[i], toValueRef(message.values[i])});
    }
    const int64_t ts = message.embedded_timestamp_ns.value_or(recv_ns);
    return writeHost().appendBoundRecord(binding.topic, PJ::Timestamp{ts}, PJ::Span<const PJ::sdk::BoundFieldValue>(row_));
  }

  mavlink_detail::MavlinkDialog dialog_;
  std::unique_ptr<mavlink_detail::Transport> transport_;
  mav::StreamParser parser_;
  std::vector<mav::Message> messages_;
  std::map<std::string, TopicBinding> bindings_;
  std::vector<PJ::sdk::BoundFieldValue> row_;
};

}  // namespace

PJ_DIALOG_PLUGIN(mavlink_detail::MavlinkDialog, kMavlinkManifest)
PJ_DATA_SOURCE_PLUGIN(MavlinkSource, kMavlinkManifest)
